version: '3'
services:
  mybooks:
    image: "gyimix/mybooks"
    build:
      context: mybooks2/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - nw
  bookstore:
    image: "gyimix/bookstore"
    build:
      context: bookstore/.
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MYBOOKS_HOST=mybooks
      - MYBOOKS_PORT=8080
    networks:
      - nw
networks:
  nw: