spring:
  messages:
    basename: i18n.messages
quiz:
  quiz-locale-config-list:
    - id: 1
      name: en-US
      request-text: For the quiz in English, enter
    - id: 2
      name: ru-RU
      request-text: Для проведения викторины на русском, введите
  quiz-locale-name: en-US
