spring:
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false
quiz:
  quiz-locale-config-list:
    - id: 1
      name: en-US
      request-text: For the quiz in English, enter
    - id: 2
      name: ru-RU
      request-text: Для проведения викторины на русском, введите
    - id: 3
      name: hu-HU
      request-text: For unsupported Hungarian quiz (default lang), enter
  quiz-locale-name: en-US
  csv-file-name: questions.csv
