spring:
  datasource:
    url: jdbc:h2:mem:testdb
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false
  shell:
    interactive:
      enabled: true
mybooks:
  default-locale-tag: ru-RU
