version: '3'
services:
  mybooks:
    image: "gyimix/mybooks"
    build:
      context: mybooks/.
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - mybooksnet

  bookstore:
    image: "gyimix/bookstore"
    build:
      context: bookstore/.
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      MYBOOKS_HOST: mybooks:8080
      KAFKA_SERVER: kafka:9092
      KAFKA_TOPIC: book-sales
    networks:
      - mybooksnet

  bookseller:
    image: "gyimix/bookseller"
    depends_on:
      - kafka
    build:
      context: bookseller/.
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      KAFKA_SERVER: kafka:9092
      KAFKA_TOPIC: book-sales
    networks:
      - mybooksnet

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - mybooksnet

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mybooksnet

networks:
  mybooksnet: